//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.15 at 05:03:11 ���� CST 
//

package com.sfxie.data.xml.request;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlbeans.golive.com/schema/request}device"/>
 *         &lt;element ref="{http://xmlbeans.golive.com/schema/request}user"/>
 *         &lt;element ref="{http://xmlbeans.golive.com/schema/request}data"/>
 *       &lt;/sequence>
 *       &lt;attribute name="iname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="apktype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="region" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "device",
    "user",
    "data"
})
@XmlRootElement(name = "parameter")
public class Parameter {

    @XmlElement(required = true)
    protected Device device;
    @XmlElement(required = true)
    protected User user;
    @XmlElement(required = true)
    protected Data data;
    @XmlAttribute(required = true)
    protected String iname;
    @XmlAttribute(required = true)
    protected String apktype;
    @XmlAttribute(required = true)
    protected String language;
    @XmlAttribute(required = true)
    protected String region;

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link Device }
     *     
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link Device }
     *     
     */
    public void setDevice(Device value) {
        this.device = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the iname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIname() {
        return iname;
    }

    /**
     * Sets the value of the iname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIname(String value) {
        this.iname = value;
    }

    /**
     * Gets the value of the apktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApktype() {
        return apktype;
    }

    /**
     * Sets the value of the apktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApktype(String value) {
        this.apktype = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
