//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.15 at 05:03:11 ���� CST 
//

package com.sfxie.data.xml.request;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dnum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="didtoken" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="devmodel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dver" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="devtype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clienttype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mac" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deviceid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "device")
public class Device {

    @XmlAttribute(required = true)
    protected String dnum;
    @XmlAttribute(required = true)
    protected String didtoken;
    @XmlAttribute(required = true)
    protected String devmodel;
    @XmlAttribute(required = true)
    protected String dver;
    @XmlAttribute(required = true)
    protected String devtype;
    @XmlAttribute(required = true)
    protected String clienttype;
    @XmlAttribute(required = true)
    protected String mac;
    @XmlAttribute(required = true)
    protected String deviceid;

    /**
     * Gets the value of the dnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnum() {
        return dnum;
    }

    /**
     * Sets the value of the dnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnum(String value) {
        this.dnum = value;
    }

    /**
     * Gets the value of the didtoken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDidtoken() {
        return didtoken;
    }

    /**
     * Sets the value of the didtoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDidtoken(String value) {
        this.didtoken = value;
    }

    /**
     * Gets the value of the devmodel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevmodel() {
        return devmodel;
    }

    /**
     * Sets the value of the devmodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevmodel(String value) {
        this.devmodel = value;
    }

    /**
     * Gets the value of the dver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDver() {
        return dver;
    }

    /**
     * Sets the value of the dver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDver(String value) {
        this.dver = value;
    }

    /**
     * Gets the value of the devtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevtype() {
        return devtype;
    }

    /**
     * Sets the value of the devtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevtype(String value) {
        this.devtype = value;
    }

    /**
     * Gets the value of the clienttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClienttype() {
        return clienttype;
    }

    /**
     * Sets the value of the clienttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClienttype(String value) {
        this.clienttype = value;
    }

    /**
     * Gets the value of the mac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMac() {
        return mac;
    }

    /**
     * Sets the value of the mac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMac(String value) {
        this.mac = value;
    }

    /**
     * Gets the value of the deviceid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * Sets the value of the deviceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceid(String value) {
        this.deviceid = value;
    }

}
